In [60]:
import numpy as np

array = np.array(range(5)) 

In [61]:
array = np.array(range(5))
array2d= np.array([range(5),range(5)])

# Array Basics
- array.shape --> shape of array.

- array.size --> size of array.

- array.ndim --> array dimension.

- array.T.shape -->  shape of array after transpose.

- array.reshape(x, y) -->  reshape array to a new array with(x, y) dimensions.


In [62]:
print(array.shape)
print(array2d.size)
print(array2d.T.shape)
print(array2d.ndim)
print(array2d.reshape(2,5))

(5,)
10
(5, 2)
2
[[0 1 2 3 4]
 [0 1 2 3 4]]


# Array Creation
- np.ones((rows, cols), dtype) --> Creates an array of ones of a given size(by default dtype == float).

- np.zeros((rows, cols), dtype) --> Creates an array of ones of a given size(by default dtype == float).

- np.arange((start, stop), step) --> Creates an array of integers with given start & stop values, and a step size(only stop is required, and is not inclusive).

- np.linspace((start, stop), n) --> Creates an array of floats with given start & stop values with n elements, seperated by a consistent tep size   (stop is inclusive).


In [63]:
ones = np.ones(4,)
print(f" zeros---> {ones}\n")
zeros = np.zeros((2, 5), dtype=int)
print(f" ones---> {zeros}\n")
arange = np.arange(10)
print(f" arange---> {arange}\n")
linspace = np.linspace(0, 100, 5)
print(f" linspace---> {linspace}\n"  )
example = np.arange(1, 9 ,2).reshape(2,2)
print("-->generating odd numbers from 1 to 9 (step =2), reshape into 2x2 array\n")
print(f" example---> {example}\n")
identity = np.identity(10)
print(f"identity matrix ---> {identity}")
# s = np.linspace(0, 100 , 10) since '0' is included , step must be '11' and not '10' to get 0, 10, 20 ,...
s = np.linspace(0, 100 , 11)
print(s)

 zeros---> [1. 1. 1. 1.]

 ones---> [[0 0 0 0 0]
 [0 0 0 0 0]]

 arange---> [0 1 2 3 4 5 6 7 8 9]

 linspace---> [  0.  25.  50.  75. 100.]

-->generating odd numbers from 1 to 9 (step =2), reshape into 2x2 array

 example---> [[1 3]
 [5 7]]

identity matrix ---> [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Random Number Arrays
## in order to generate random number we need random generator
- np.default_rng(seed) --> Creates random number generator(the seed is for reproducibility).

- rng.random(n) --> Returns n random numbers from a uniform distribution between 0 and 1.

- rng.normal(mean, stdev, n) --> Returns n random number from a normal distribution with a given mean and standart deviation.



In [64]:
from numpy.random import  default_rng

In [67]:
rng = default_rng(12345) #seed = 12345
random_arr = rng.random(10)
random_arr


array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [66]:
mean, stdev = 5, 1
random_normal = rng.normal(mean, stdev, size=10)
random_normal

array([6.32229806, 4.70030148, 5.90291934, 3.37841727, 4.84181074,
       5.44948393, 3.65639893, 4.91831241, 6.72473993, 7.61815943])

In [69]:
integers = rng.integers(0, 10, 100)
integers

array([5, 2, 1, 2, 9, 2, 6, 2, 8, 4, 5, 2, 6, 4, 7, 2, 6, 8, 4, 1, 0, 8,
       5, 1, 2, 7, 3, 6, 8, 2, 8, 7, 3, 2, 3, 0, 4, 6, 7, 5, 1, 6, 0, 1,
       9, 2, 5, 6, 8, 0, 8, 8, 6, 4, 2, 6, 6, 3, 6, 1, 2, 0, 2, 2, 8, 8,
       8, 9, 6, 4, 5, 3, 4, 2, 6, 9, 1, 0, 3, 4, 4, 1, 1, 2, 5, 7, 4, 2,
       4, 5, 9, 3, 2, 5, 0, 3, 1, 2, 1, 2])